### PR TITLE
Introducing the data frame

### PR DESCRIPTION
**Pull request by huntc**
This PR introduces the data frame to convey flip-flop-app payloads. A means to version the protocol, determine the source of the frame (client/server), the server address and port and Message Authentication Code (MAC) to authenticate the data are all provided.

### CODE REVIEW

**Comment by arnolddevos** [comment]
As a general comment I think you are right to have the error detection, encryption, framing and addressing at this level.   These are all transport issues independent of the application protocol.

**Comment by arnolddevos** [comment]
Are you being a bit miserly with the header size?  No doubt you have considered this, but a greater range of station addresses and port numbers might be useful.

**Comment by arnolddevos** [comment]
We could have a prose description of this level of the protocol.  How much is implied beyond the wire format?  I think the media access rules could stand at this level.

**Comment by arnolddevos** [comment]
Why confine the encryption implementation to the tests?  If the aim is to exclude (most) implementation from this library then fair enough.  In that case we could have another library with the encryption implementation.

**Comment by huntc** [comment]
> Are you being a bit miserly with the header size? No doubt you have considered this, but a greater range of station addresses and port numbers might be useful.

I might be. I'm keeping RS485 in mind given the max number of servers on the bus being around 32. We can always restructure the protocol though by bumping its version if necessary.

**Comment by huntc** [comment]
> We could have a prose description of this level of the protocol. How much is implied beyond the wire format? I think the media access rules could stand at this level.

We do have the primary README and the examples to back it up. Happy to add more but might need your help there.

**Comment by huntc** [comment]
> Why confine the encryption implementation to the tests? If the aim is to exclude (most) implementation from this library then fair enough. In that case we could have another library with the encryption implementation.

Encryption is an external concern because there are different ways of going about it. For example, we can use the libraries we have here in the tests. However, we can also use the hardware accelerated CCM peripheral of the nRF52840.

Further, I'm probably going to avoid encryption in our actual implementation on the nRF52840 in the first instance. But I needed to do it here to explore the implications.

**Review by arnolddevos — APPROVED** [review]

**Pull request merged**
